# Generated by Django 5.2.13 on 2026-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.users') IS NOT NULL AND to_regclass('public.usuarios') IS NULL THEN
                            ALTER TABLE public.users RENAME TO usuarios;
                        ELSIF to_regclass('public.usuarios') IS NULL THEN
                            CREATE TABLE public.usuarios (
                                id uuid PRIMARY KEY,
                                nome varchar(100) NOT NULL,
                                email varchar(254) NOT NULL UNIQUE
                            );
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.usuarios') IS NOT NULL AND to_regclass('public.users') IS NULL THEN
                            ALTER TABLE public.usuarios RENAME TO users;
                        END IF;
                    END
                    $$;
                    """,
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name="UserModel",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ("nome", models.CharField(max_length=100)),
                        ("email", models.EmailField(max_length=254, unique=True)),
                    ],
                    options={
                        "db_table": "usuarios",
                    },
                )
            ],
        )
    ]
