repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - django
          - django-stubs
          - django-cors-headers
          - django-environ
          - djangorestframework
          - djangorestframework-stubs
          - djangorestframework-simplejwt
          - drf-spectacular
          - psycopg2-binary
          - whitenoise
