services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recreionasferias_web
    restart: always
    command: sh scripts/run.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: recreionasferias_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
