# Generated by Django 5.2.16 on 2026-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("definicoes_polos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="definicaopolo",
            name="resultado_final_de_inscritos",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Quantidade final de inscritos após considerar todas as projeções e ajustes.",
                verbose_name="Resultado final de inscritos",
            ),
        ),
        migrations.AlterField(
            model_name="definicaopolo",
            name="ponto_focal_email",
            field=models.CharField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="E-mail do ponto focal",
            ),
        ),
    ]
