# Generated by Django 5.2.16 on 2026-10-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("definicoes_polos", "0002_definicaopolo_resultado_final_de_inscritos_and_more"),
        ("polos", "0004_ponto_focal_no_polo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="definicaopolo",
            name="ponto_focal_nome",
        ),
        migrations.RemoveField(
            model_name="definicaopolo",
            name="ponto_focal_telefone",
        ),
        migrations.RemoveField(
            model_name="definicaopolo",
            name="ponto_focal_email",
        ),
    ]
