# Generated by Django 5.2.16 on 2026-08-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_seed_cargos_permitidos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="cargos_snapshot",
        ),
        migrations.AddField(
            model_name="usuario",
            name="cargo_permitido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="core.cargopermitido",
                to_field="uuid",
            ),
        ),
    ]
