# Generated by Django 5.2.16 on 2026-08-26 15:05

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Polo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "codigo_eol",
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(6)
                        ],
                        verbose_name="Código EOL",
                    ),
                ),
                (
                    "nome_polo",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Nome do polo",
                    ),
                ),
                (
                    "nome_osc",
                    models.CharField(
                        max_length=255, verbose_name="Nome da OSC"
                    ),
                ),
                (
                    "dre_nome",
                    models.CharField(
                        max_length=255, verbose_name="Nome da DRE"
                    ),
                ),
                (
                    "dre_codigo_eol",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        verbose_name="Código EOL da DRE",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("oficial", "Polo oficial"),
                            ("reserva", "Polo reserva"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "gestao",
                    models.CharField(
                        choices=[
                            ("parceira", "Parceira"),
                            ("direta", "Direta"),
                        ],
                        default="parceira",
                        max_length=20,
                        verbose_name="Gestão",
                    ),
                ),
                (
                    "tipo_ue",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="Tipo de UE",
                    ),
                ),
                (
                    "quantidade_maxima_alunos",
                    models.PositiveIntegerField(
                        verbose_name="Quantidade máxima de alunos"
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=9,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "tipo_logradouro",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Tipo de logradouro",
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Logradouro",
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Número",
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "nome_gestor",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nome do gestor",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "observacoes_gerais",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Observações gerais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Polo",
                "verbose_name_plural": "Polos",
                "ordering": ("nome_polo",),
            },
        ),
    ]
