# Generated by Django 5.2.16 on 2026-09-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleSincronizacaoPolos",
            fields=[
                (
                    "chave",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Chave",
                    ),
                ),
                (
                    "ultima_execucao_em",
                    models.DateTimeField(verbose_name="Última execução"),
                ),
            ],
            options={
                "verbose_name": "Controle de sincronização de polos",
                "verbose_name_plural": "Controles de sincronização de polos",
            },
        ),
    ]
