# Generated by Django 5.2.16 on 2026-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polos", "0002_controle_sincronizacao_polos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polo",
            name="email",
            field=models.CharField(
                blank=True, default="", max_length=254, verbose_name="E-mail"
            ),
        ),
    ]
