# Generated by Django 5.2.16 on 2026-10-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polos", "0003_alter_polo_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="polo",
            name="ponto_focal_email",
            field=models.CharField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="E-mail do ponto focal",
            ),
        ),
        migrations.AddField(
            model_name="polo",
            name="ponto_focal_nome",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Nome do ponto focal",
            ),
        ),
        migrations.AddField(
            model_name="polo",
            name="ponto_focal_telefone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                verbose_name="Telefone do ponto focal",
            ),
        ),
        migrations.AlterField(
            model_name="polo",
            name="nome_polo",
            field=models.CharField(
                max_length=255, verbose_name="Nome do polo"
            ),
        ),
    ]
