# Generated by Django 5.2.16 on 2026-09-23 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("edicoes", "0001_initial"),
        ("polos", "0003_alter_polo_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo_estudante",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESTUDANTE_DA_REDE", "Estudante da rede"),
                            ("ESTUDANTE_EXTERNO", "Estudante externo"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="Tipo de estudante",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BERCARIO_I", "Berçário I"),
                            ("BERCARIO_II", "Berçário II"),
                            ("MINI_GRUPO_I", "Mini Grupo I"),
                            ("MINI_GRUPO_II", "Mini Grupo II"),
                            ("QUATRO_A_14_ANOS", "4 a 14 anos"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "codigo_eol",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Código EOL",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=14,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "nome_participante",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nome do participante",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de nascimento",
                    ),
                ),
                (
                    "responsavel_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nome do responsável",
                    ),
                ),
                (
                    "responsavel_nome_social",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nome social do responsável",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=9,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "tipo_logradouro",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Tipo de logradouro",
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Logradouro",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Número",
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "telefone_contato_1",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Telefone de contato 1",
                    ),
                ),
                (
                    "telefone_contato_2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Telefone de contato 2",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "dre_codigo_eol",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Código EOL da DRE",
                    ),
                ),
                (
                    "dre_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nome da DRE",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("COMPLETA", "Completa"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "edicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="edicoes.edicao",
                        verbose_name="Edição",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="polos.polo",
                        verbose_name="Polo de inscrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição",
                "verbose_name_plural": "Inscrições",
                "ordering": ("-criado_em",),
            },
        ),
    ]
