BEGIN;
--
-- Create model Usuario
--
CREATE TABLE "usuarios_conta" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "rf" varchar(32) NOT NULL UNIQUE, "nome_completo" varchar(255) NOT NULL, "cpf" varchar(11) NOT NULL, "contexto" varchar(100) NOT NULL, "permissoes_rbac" jsonb NOT NULL, "inexistente_eol" boolean NOT NULL, "atualizado_em" timestamp with time zone NOT NULL);
CREATE TABLE "usuarios_conta_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "usuarios_conta_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "usuarios_conta_rf_b0062dbf_like" ON "usuarios_conta" ("rf" varchar_pattern_ops);
ALTER TABLE "usuarios_conta_groups" ADD CONSTRAINT "usuarios_conta_groups_usuario_id_group_id_34a83e10_uniq" UNIQUE ("usuario_id", "group_id");
ALTER TABLE "usuarios_conta_groups" ADD CONSTRAINT "usuarios_conta_groups_usuario_id_d55066d7_fk_usuarios_conta_id" FOREIGN KEY ("usuario_id") REFERENCES "usuarios_conta" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usuarios_conta_groups" ADD CONSTRAINT "usuarios_conta_groups_group_id_e0478673_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "usuarios_conta_groups_usuario_id_d55066d7" ON "usuarios_conta_groups" ("usuario_id");
CREATE INDEX "usuarios_conta_groups_group_id_e0478673" ON "usuarios_conta_groups" ("group_id");
ALTER TABLE "usuarios_conta_user_permissions" ADD CONSTRAINT "usuarios_conta_user_perm_usuario_id_permission_id_1134cf0b_uniq" UNIQUE ("usuario_id", "permission_id");
ALTER TABLE "usuarios_conta_user_permissions" ADD CONSTRAINT "usuarios_conta_user__usuario_id_70855360_fk_usuarios_" FOREIGN KEY ("usuario_id") REFERENCES "usuarios_conta" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usuarios_conta_user_permissions" ADD CONSTRAINT "usuarios_conta_user__permission_id_d31f2b9c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "usuarios_conta_user_permissions_usuario_id_70855360" ON "usuarios_conta_user_permissions" ("usuario_id");
CREATE INDEX "usuarios_conta_user_permissions_permission_id_d31f2b9c" ON "usuarios_conta_user_permissions" ("permission_id");
COMMIT;
