# Generated by Django 5.2.16 on 2026-08-20 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome que identifica a edição. Não pode se repetir entre edições.",
                        max_length=255,
                        unique=True,
                        verbose_name="Nome da edição",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        verbose_name="Início do período da edição"
                    ),
                ),
                (
                    "data_fim",
                    models.DateField(verbose_name="Fim do período da edição"),
                ),
                (
                    "inscricoes_inicio",
                    models.DateField(
                        verbose_name="Início do período de inscrições"
                    ),
                ),
                (
                    "inscricoes_fim",
                    models.DateField(
                        verbose_name="Fim do período de inscrições"
                    ),
                ),
                (
                    "quantidade_inscritos",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Consolidação das inscrições realizadas no sistema.",
                        verbose_name="Quantidade de inscritos",
                    ),
                ),
                (
                    "quantidade_atendimento_efetivo",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Consolidação das aferições cadastradas no sistema.",
                        verbose_name="Quantidade de atendimento efetivo",
                    ),
                ),
                (
                    "quantidade_passeios",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text='Quantidade de atividades com a categoria "Passeio".',
                        verbose_name="Quantidade de passeios",
                    ),
                ),
                (
                    "quantidade_apresentacoes",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text='Quantidade de atividades com a categoria "Apresentação".',
                        verbose_name="Quantidade de apresentações",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejada", "Planejada"),
                            ("ativa", "Ativa"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="planejada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edição",
                "verbose_name_plural": "Edições",
                "ordering": ("data_inicio", "nome"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ativa")),
                        fields=("status",),
                        name="unica_edicao_ativa",
                    )
                ],
            },
        ),
    ]
