"""Serializer da consulta de participante da rede."""

from rest_framework import serializers


class ParticipanteRedeSerializer(serializers.Serializer):
    """Contrato público do participante enriquecido pela EOL."""

    codigo_aluno = serializers.IntegerField()
    codigo_eol = serializers.CharField(source="codigo_aluno")
    tipo_turno = serializers.IntegerField()
    ano_letivo = serializers.IntegerField()
    nome_aluno = serializers.CharField()
    nome_participante = serializers.CharField(source="nome_aluno")
    nome_social_aluno = serializers.CharField()
    codigo_situacao_matricula = serializers.IntegerField()
    situacao_matricula = serializers.CharField()
    data_situacao = serializers.CharField()
    data_nascimento = serializers.CharField()
    numero_aluno_chamada = serializers.CharField()
    codigo_turma = serializers.IntegerField()
    nome_responsavel = serializers.CharField()
    responsavel_nome = serializers.CharField(source="nome_responsavel")
    responsavel_nome_social = serializers.CharField()
    tipo_responsavel = serializers.CharField()
    celular_responsavel = serializers.CharField()
    telefone_contato_1 = serializers.CharField(source="celular_responsavel")
    telefone_contato_2 = serializers.CharField()
    email = serializers.CharField()
    data_atualizacao_contato = serializers.CharField()
    codigo_tipo_turma = serializers.IntegerField()
    turma_nome = serializers.CharField()
    etapa_ensino = serializers.CharField()
    ciclo_ensino = serializers.CharField()
    desc_etapa_ensino = serializers.CharField()
    desc_ciclo_ensino = serializers.CharField()
    data_atualizacao_tabela = serializers.CharField()
    nome_mae = serializers.CharField()
    sexo = serializers.CharField()
    grupo_etnico = serializers.CharField()
    nacionalidade = serializers.CharField()
    eh_imigrante = serializers.BooleanField()
    nis = serializers.CharField()
    cns = serializers.CharField()
    numero = serializers.CharField()
    complemento = serializers.CharField()
    bairro = serializers.CharField()
    cep = serializers.CharField()
    cidade = serializers.CharField()
    uf = serializers.CharField()
    tipo_logradouro = serializers.CharField()
    logradouro = serializers.CharField()
